---
title: "cielo_manuscriptanalyses"
author: "Hannah Lunkenheimer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      cache = TRUE)

library(moonBook)
library(dplyr)
library(readr)
library(ggplot2)
library(sjPlot)
library(lme4)
library(car)
library(DHARMa)
library(janitor)
library(reshape2)
library(ggsignif)
library(stats)
library(ggpubr)
library(tidyr)
# importing the data
d_all <- read_csv("data/Cielo1_MergedFull_practice.csv")

# now let's view our data
#View(d_all)

# some participant data needs to be thrown out completely according to the red rows in our CSV file, so let's remove those participants completely here (ID 129, 152, 175, and 277)
d_all <- subset(d_all, id_num != "129" & id_num != "152" & id_num != "175" & id_num != "277")
# great, we've removed our 4 participants completely from our dataframe d_all and now have all of the participants we can use for analyses
```

## Recoding everything

```{r recoding variables}
# gender
#d_all$gender <- dplyr::recode(d_all$gender, 'Male' = 1, 'Female'=2, 'Other' = 3)

# control
d_all$control <- dplyr::recode(d_all$control...6, 'Really Disagree' = 6, 'Disagree'=5, 'Kind of Disagree' = 4, 'Kind of Agree' = 3, 'Agree' = 2, 'Really Agree' = 1)

# religiosity
d_all$relig_attendserv <- dplyr::recode(d_all$relig_attendserv, 'Never' = 1, 'Less than once a year'=2, 'A few times a year' = 3, 'A few times a month' = 4, 'A few times a week' = 5, 'Daily' = 6)
d_all$relig_tradition <- dplyr::recode(d_all$relig_tradition, 'Not at all important' = 1, 'Minimally important'=2, 'Moderately important' = 3, 'Very important' = 4)

# sure
d_all$godcertainty <- ifelse(d_all$exist_sure_god == "A little sure", 1, 
                               ifelse(d_all$exist_sure_god == "Very sure", 2, NA))
# parent beliefs
d_all$relig_describe_god <- dplyr::recode(d_all$relig_describe_god, 'I do not believe in God.' = 1, 'A non-interventionist God; one who does not attempt to influence events in human life.' = 2, 'A God who used to intervene in historical or biblical times, but is not particularly involved in the workings of modern life.' = 3, 'An interventionist God; one who is sometimes involved in the workings of modern life.' = 4, 'An interventionist God; one who is intimately involved in the workings of modern life.' = 5)
d_all$relig_intervene <- dplyr::recode(d_all$relig_attendserv, 'Absolutely not' = 1, 'Probably not'=2, 'Unsure' = 3, 'Probably yes' = 4, 'Absolutely yes' = 5)

# god's intervention columns 
d_all <- d_all %>% 
  mutate_at(vars(49:62),
   ~as.numeric(dplyr::recode(.,
    "Never"= 1,
    "Only at special times"= 2,
    "Pretty often"= 3,
    "Always"= 4,
    "always" = 4,
    "IDK" = 5)))

#binary focal interview questions
d_all <- d_all %>% 
  mutate_at(vars(43:47),
   ~as.numeric(dplyr::recode(.,
    "No"= 1,
    "Sometimes"= 2,
    "Yes"= 3,
    "IDK"= 0)))

d_all$rpers_happen <- dplyr::recode(d_all$rpers_happen, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 0)

#using the janitor package
d_all$school <- tolower(d_all$school)


#d_all$godcertainty <- recode(d_all$exist_sure_god, 'A little sure' = 1, "Very sure" = 2)

```

## Creating scores

```{r summed scores for everything, echo=FALSE}
#family religiosity (higher scores indicate higher levels of religiosity from 0 to 10)
d_all$famreligiosity <- d_all$relig_attendserv + d_all$relig_tradition

#parent beliefs (higher scores indicate stronger beliefs in god as interventionist from 0 to 10)
d_all$parentbelief <- d_all$relig_describe_god + d_all$relig_intervene

#intervention by domains from factor analysis and design
d_all$environment <- rowSums(d_all[,c(50, 51, 52)]/3) #plants, sun, seasons
d_all$psych <- rowSums(d_all[,c(55, 57, 60, 61)]/4) #dreams, happy, brave, decisions
d_all$health <- rowSums(d_all[,c(49, 62)]/2) #sick, safe
d_all$achieve <- rowSums(d_all[,c(56, 58, 59)]/3) #job, sports, find
d_all$social <- rowSums(d_all[,c(53, 54)]/2) #love, friends
d_all$alldomains <- rowSums(d_all[,c(49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62)]/14)
d_all$people <- rowSums(d_all[,c(55, 57, 60, 61, 49, 62, 56, 58, 59, 53, 54)]/11)

#4 intervention open-ended interview score
d_all$interview <- rowSums(d_all[,c(43, 45, 47, 64)]/4)

#in case i need code to filter out IDK responses from analyses
# d_interview2 <- dplyr::filter(d_interview, rgod_happen_earth != 4) 

```

### Does certainty in God's being real differ across age?

```{r God certainty changes in age?}
#creating a plot and regressions to see if there are any changes in real/pretend god certainty 
godcertainty1 <- lm(godcertainty ~ age + parentbelief + famreligiosity + gender + age*parentbelief + age*famreligiosity, data = d_all)
summary(godcertainty1)
godcertainty2 <- lm(godcertainty ~ parentbelief + famreligiosity + gender + age*parentbelief + age*famreligiosity, data = d_all)
summary(godcertainty2)
AIC(godcertainty1, godcertainty2)

tab_model(godcertainty1, godcertainty2)


summary(godcertainty2)
anova(godcertainty1, godcertainty2)

```

### Does God's intervention differ when we orient children using different techniques of framing?

```{r general intervention framing}
#open ended counts for intervention in various contexts

d_framing <- d_all %>% dplyr::select(contains(c("age", "rgod_happen_earth", "rgod_happen_ever", "rgod_happen_lives", "rpers_happen", "id_num")))

#d_openended$gender <- as.factor(d_openended$gender)

#omitting NAs
d_framing <- na.omit(d_framing)

# let's convert our data to tall format so we can include all of the same plots on the same figure
d_framing_reshaped <- melt(d_framing, id.vars= c("age", "id_num"))

d_framing_reshaped$value <- as.factor(d_framing_reshaped$value)

# here, i'm making a dataframe with frequency counts added in
d_openended_reshaped_counts <- table(d_framing_reshaped$value, d_framing_reshaped$variable, d_framing_reshaped$id_num)
addmargins(d_openended_reshaped_counts)
round(prop.table(d_openended_reshaped_counts,2)*100,digits=0)
df_openended <- as.data.frame(d_openended_reshaped_counts)


plot_framing <- ggplot(data = d_framing_reshaped, aes(x = value, fill = variable)) +
      geom_bar(aes(fill = value),stat = "count",position = "dodge") + 
      theme_classic() +
      labs(title="Children's responses to God interventionist framing questions", x ="Item", y = "Counts", fill = "Response") +
      theme(axis.text.x = element_text(angle=90))

# fixing the x axis labels
plot_framing <- plot_framing + scale_fill_discrete(labels=c("1" = "No", "2" = "Sometimes", "3" = "Yes", "4" = "I don't know"))

plot_framing

# numbers for happen on earth, no = 7, sometimes = 8, yes = 115, IDK = 4
# numbers for happen ever on earth, no = 3, sometimes = 12, yes = 114, IDK = 3
# numbers for happen in people's lives, no = 8, sometimes = 11, yes = 108, IDK = 5
# numbers for happen ever on earth, no = 23, sometimes = 1, yes = 97, IDK = 11

# let's run t tests for mean differences in the yes/sometimes responses


#d_openended2 <- d_all %>% dplyr::select(contains(c("age", "rgod_happen_earth", "rgod_happen_ever", "rgod_happen_lives", "rpers_happen", "id_num")))

#d_openended2 <- dplyr::filter(d_openended2, rgod_happen_earth != 4, rgod_happen_earth != 1) 
#d_openended2 <- dplyr::filter(d_openended2, rgod_happen_ever != 4, rgod_happen_ever != 1) 
#d_openended2 <- dplyr::filter(d_openended2, rgod_happen_lives != 4, rgod_happen_lives != 1) 
#d_openended2 <- dplyr::filter(d_openended2, rpers_happen != 4, rpers_happen != 1) 

plot_framing <- ggplot(d_framing_reshaped, aes(fill=variable, x=value)) + 
    geom_bar(position="dodge", stat="count") 
    
# fixing the x axis labels
plot_framing <- plot_framing + scale_x_discrete(labels=c("1" = "No", "2" = "Sometimes", "3" = "Yes", "0" = "I don't know")) +
    scale_fill_brewer(palette= "Paired") +
  theme_minimal()

plot_framing

```
```{r chi square to look at differences in personal life intervention vs peoples lives}
d_personal <- d_all %>% dplyr::select("rpers_happen", "rgod_happen_lives", "rgod_happen_earth", "rgod_happen_ever")

d_personal$rpers_happen <- dplyr::recode(d_personal$rpers_happen, '1' = 1, '2'=1, '3' = 2, '0' = 1)
d_personal$rgod_happen_lives <- dplyr::recode(d_personal$rgod_happen_lives, '1' = 1, '2'=1, '3' = 2, '0' = 1)
d_personal$rgod_happen_earth <- dplyr::recode(d_personal$rgod_happen_earth, '1' = 1, '2'=1, '3' = 2, '0' = 1)
d_personal$rgod_happen_ever <- dplyr::recode(d_personal$rgod_happen_ever, '1' = 1, '2'=1, '3' = 2, '0' = 1)


# Convert the data to a long format
d_personal_long <- d_personal %>%
  pivot_longer(cols = everything())

# Create a contingency table of the data
mytable <- table(d_personal_long)

# Run the chi-square test of independence
result <- chisq.test(mytable)

# View the results
result

prop.table(mytable, margin = 1)

chisq.test(d_personal$rpers_happen, d_personal$rgod_happen_lives, correct=FALSE)
chisq.test(d_personal$rpers_happen, d_personal$rgod_happen_earth, correct=FALSE)
chisq.test(d_personal$rpers_happen, d_personal$rgod_happen_ever, correct=FALSE)
chisq.test(d_personal$rgod_happen_lives, d_personal$rgod_happen_ever, correct=FALSE)
chisq.test(d_personal$rgod_happen_lives, d_personal$rgod_happen_earth, correct=FALSE)
chisq.test(d_personal$rgod_happen_earth, d_personal$rgod_happen_ever, correct=FALSE)

# this is what i reported in the paper
chisq.test(d_personal_long$name, d_personal_long$value, correct=FALSE)
```
### How do I do this? Mixed effects model
```{r intervention framing mixed effects model}
#creating dataframe for intervention framing fem
d_framingreg <- d_all %>% dplyr::select("control", contains(c("age", "rgod_happen_earth", "rgod_happen_ever", "rgod_happen_lives", "rpers_happen", "id_num", "gender", "famreligiosity", "parentbelief", "school", "interview")))

#want to reshape to see if test q as iv
d_framing_reshapedreg <- melt(d_framingreg, id.vars= c("age", "id_num", "interview", "gender", "famreligiosity", "control", "parentbelief", "school"))

#model with everything, lots of errors/warnings/failure to converge
mod_frame1 <- lmer(interview ~ age + parentbelief + school + famreligiosity + variable + (1|id_num), data = d_framing_reshapedreg)
vif(mod_frame1)
tab_model(mod_frame1)
summary(mod_frame1)
#CI <- conditionIndex(mod_frame1)

#model with removed items to try to make simple
mod_frame2 <- lmer(interview ~ parentbelief + famreligiosity + variable + (1|id_num), data = d_framing_reshapedreg)
vif(mod_frame2)
tab_model(mod_frame2)
summary(mod_frame2)
#CI <- conditionIndex(mod_frame2)

mod_frame3 <- lmer(interview ~ parentbelief + variable + (1|id_num), data = d_framing_reshapedreg)
tab_model(mod_frame3)
summary(mod_frame3)
#CI <- conditionIndex(mod_frame3)

mod_frame4 <- lm(interview ~ parentbelief + variable, data = d_framing_reshapedreg)
tab_model(mod_frame4)
summary(mod_frame4)

#mod_frame1 <- lmer(interview ~ age + parentbelief + school + famreligiosity + variable + (1|id_num), 
#                   data = d_framing_reshapedreg, 
#                   control = lmerControl(optimizer = "bobyqa", 
#                                         optCtrl = list(maxfun = 100000),
#                                         check = ctrl_check_list(warn_singular = FALSE),
#                                         check.conv = ctrl_check_list(action = "warning"),
#                                         check.grad = ctrl_check_list(action = "warning")))
#

```


```{r summed scores for all vignette domains, echo=FALSE}
# we start by creating our null model with a fixed slope and no predictors
null_model <- lm(alldomains ~ 1, data = d_all)
summary(null_model)
coef(null_model)

reg1 <- lm(alldomains ~ age, data = d_all)
summary(reg1)
coef(reg1)

reg2 <- lm(alldomains ~ age, data = d_all)
summary(reg2)
coef(reg2)

reg3 <- lm(alldomains ~ age + school + famreligiosity + control, data = d_all)
summary(reg3)
anova(reg3)
coef(reg3)

reg4 <- lm(alldomains ~ age + school + famreligiosity + parentbelief + control, data = d_all)
summary(reg4)
coef(reg4)

reg6 <- lm(alldomains ~ age + school + famreligiosity + control + parentbelief + age*famreligiosity + age*control + famreligiosity*control + parentbelief*age + parentbelief*famreligiosity + parentbelief*control, data = d_all)
summary(reg6)

```

```{r looking at means diffs in domains}
d_domain <- d_all %>% dplyr::select(starts_with("achieve"), starts_with("health"), starts_with("psych"), starts_with("social"), starts_with("environment"), starts_with("id_num"), "age", "people", "alldomains") 

d_domain2 <- d_all %>% dplyr::select(starts_with("achieve"), starts_with("health"), starts_with("psych"), starts_with("social"), starts_with("environment"), starts_with("id_num")) 

d_domain_long2 <- melt(d_domain2, id.vars= c("id_num"))

d_domain_long2$variable <- factor(d_domain_long2$variable, levels = c("achieve", "social", "health", "psych", "environment"))

domainclusters <- ggplot(data = d_domain_long2, mapping = aes(x = variable, y = value, color = variable)) + 
  geom_violin() + 
  stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..),
                 width = .7 , size = 1, linetype = "solid") +
  geom_jitter(width = .2, height = .2, alpha=.3) +
  geom_signif(comparisons = list(c("achieve", "health")), y_position = 4.00,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("achieve", "psych")), y_position = 4.25,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("achieve", "environment")), y_position = 4.5,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("social", "health")), y_position = 4.75,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("social", "psych")), y_position =5,
              map_signif_level=TRUE) +
  theme_minimal() +
  scale_color_brewer(palette= "Paired") +
  theme(legend.position = "none") +
  labs(title = "Intervention Cluster Mean Scores", x = "Domain", y = "Intervention scope") + 
  scale_x_discrete(labels=c("achieve" = "Achievement", "health" = "Health", "social" = "Social", "psych" = "Psychology", "environment" = "Nature"))
domainclusters
ggsave("domainclusters.png", domainclusters, width = 6, height = 4, dpi = 300)

# Compute the analysis of variance
anova1 <- aov(value ~ variable, data = d_domain_long)
# Summary of the analysis
summary(anova1)
TukeyHSD(anova1)

```

```{r age differences in intervention by person nature and all domains}

# how should we visualize this data?
g_environment <- ggplot(d_domain,aes(y=environment,x=age)) +
  geom_point() +
  geom_jitter() +
  geom_smooth(method="lm", color = "#E69F00") +
  theme_minimal()

# plotting our data without reg lines
g_environment

g_people <- ggplot(d_domain,aes(y=people,x=age)) +
  geom_point() +
  geom_jitter() +
  geom_smooth(method="lm", color = "#56B4E9") +
  theme_minimal()

# plotting our data without reg lines
g_people

g_total <- ggplot(d_domain,aes(y=alldomains,x=age)) +
  geom_point() +
  geom_jitter() +
  geom_smooth(method="lm", color = "#009E73") +
  theme_minimal()

# plotting our data without reg lines
g_total

#plotting regression lines on the same figure

#colors <- c("environment" = "#fdbf6f", "people" = "e2251d", "total" = "#fc9c9c")


g_allinter <- ggplot(d_domain, aes(x = age, y = alldomains)) + 
  geom_jitter(aes(age, environment, color = "Nature"), width = .2, height = .2, alpha=.3) +
  geom_smooth(aes(age, environment, color = "Nature"), method = "glm", se = FALSE) +
  geom_jitter(aes(age, social, color = "Social"), width = .2, height = .2, alpha=.3) +
  geom_smooth(aes(age, social, color = "Social"), method = "glm", se = FALSE) +
  geom_jitter(aes(age, psych, color = "Psych"), width = .2, height = .2, alpha=.3) +
  geom_smooth(aes(age, psych, color = "Psych"), method = "glm", se = FALSE) +
  geom_jitter(aes(age, achieve, color = "Achieve"), width = .2, height = .2, alpha=.3) +
  geom_smooth(aes(age, achieve, color = "Achieve"), method = "glm", se = FALSE) +
  geom_jitter(aes(age, health, color = "Health"), width = .2, height = .2, alpha=.3) +
  geom_smooth(aes(age, health, color = "Health"), method = "glm", se = FALSE) +
  theme_minimal() +
  labs(title="Children's responses to intervention frequency questions by domain cluster", x = "Age", y = "Intervention score", color = "Domain") +
  theme(axis.text.x = element_text(angle=01)) +
  scale_color_manual(values = c("#a6cfe3", "#2177b4", "#b7dd95", "#34a02b", "#fc9c9c"), name = "Domain",
                        limits = c("Achieve", "Social", "Health", "Psych", "Nature"))


g_allinter
ggsave("devdomainclusters.png", g_allinter, width = 6, height = 4, dpi = 300)

# geom_jitter(aes(age, alldomains, color = "Total"), width = .2, height = .2, alpha=.4) +
# geom_smooth(aes(age, alldomains, color = "Total"), method = "glm", se = FALSE) +

mod_environment <- lm(environment ~ age + parentbelief + famreligiosity + control, data = d_all)
summary(mod_environment)
mod_social <- lm(social ~ age + parentbelief + famreligiosity + control, data = d_all)
summary(mod_social)
mod_health <- lm(health ~ age + parentbelief + famreligiosity + control, data = d_all)
summary(mod_health)
mod_achieve <- lm(achieve ~ age + parentbelief + famreligiosity + control, data = d_all)
summary(mod_achieve)
mod_psych <- lm(psych ~ age + parentbelief + famreligiosity + control, data = d_all)
summary(mod_psych) 
mod_all <- lm(alldomains ~ age + famreligiosity + parentbelief + control, data = d_all)
summary(mod_all)

domainmanuscript <- tab_model(mod_environment, mod_achieve, mod_health, mod_social, mod_psych)

domainmanuscript


```

# How do I do this? multinomial logistic reg on child choice
```{r multinomial logreg for child choice}
library(nnet)
d_explicitconcepts <- d_all %>% dplyr::select("control", contains(c("age", "gender", "famreligiosity", "parentbelief", "explicit_concepts", "school")))
d_explicitconcepts <- na.omit(d_explicitconcepts)

d_explicitconcepts$explicit_concepts <- recode_factor(d_explicitconcepts$explicit_concepts, "Jordan, who says God doesn't really make things happen in people's lives." = "Jordan", "Riley, who says God makes things happen in people's lives, but only at special times." = "Riley", "Riley, who says God makes things happen in people's lives, but only special times." = "Riley", "Sam, who says God makes things happen in people's lives, almost every day." = "Sam")

d_explicitconcepts$explicit_concepts <- as.factor(d_explicitconcepts$explicit_concepts)

model <- multinom(explicit_concepts ~ age + control + famreligiosity + parentbelief, data = d_explicitconcepts)

```
