---
title: "Intervention Freq Factor Analysis"
author: "Hannah Lunkenheimer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(moonBook)
library(dplyr)

# importing the data
d_all <- read_csv("data/Cielo1_MergedFull_practice.csv")

# now let's view our data
#View(d_all)

# some participant data needs to be thrown out completely according to the red rows in our CSV file, so let's remove those participants completely here (ID 129, 152, 175, and 277)
subset(d_all, id_num != "129" & id_num != "152" & id_num != "175" & id_num != "277")
# great, we've removed our 4 participants completely from our dataframe d_all and now have all of the participants we can use for analyses

```

iii.	Effects of age, etc on “intervention frequency task” (Does God make..?). Would just sum number of yes responses as dv.
1.	Linear regression (+histogram of each question. Factor analysis to determine clusters)

```{r age intervention task fa}
# here is some of my old code on doing factor analysis

# we're selecting our subset of data and calling it to a new dataframe
d_fa <- d_all %>% dplyr::select(starts_with("help_"), starts_with("helop_friends")) 

# if any recoding needs to be done to the whole dataframe, we use this code below: (idk why we need to name a new df, but we do)

d_fa1 <- d_fa %>% 
  mutate_at(vars(1:14),
   ~as.numeric(dplyr::recode(.,
    "Never"=1,
    "Only at special times"=2,
    "Pretty often"=3,
    "Always"=4,
    "always" = 4,
    "IDK" = 5)))

View(d_fa1)

d_fa1 <- na.omit(d_fa1)
View(d_fa1)

# Extract number of factors
ev <- eigen(cor(d_fa1)) # get eigenvalues
ap <- parallel(subject=nrow(d_fa1),var=ncol(d_fa1),              rep=100,cent=.05)
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)

## Exploratory Factor analysis, testing with 3 factors and 2 factors to start, using varimax rotation for all
fact3 <- factanal(d_fa1, 3, rotation="varimax") 
print(fact3, digits=2, cutoff=.3, sort=TRUE)

fact2 <- factanal(d_fa1, 2, rotation="varimax") 
print(fact2, digits=2, cutoff=.3, sort=TRUE)

# this is to see if 1 factor is fine, which we'd then do a principal components analysis if this was the best loading
#fact <- factanal(d_all, 1, rotation="varimax") # show improvement 5, 4, 3
#print(fact, digits=2, cutoff=.3, sort=TRUE)

# Reduce factors- we do this to see if taking out items makes the loadings more clear. regardless of the outcome we find, it's up to our discretion as researchers on whether or not to omit certain items from a set of questions based on rationale
# d_all <- d_all %>% select(- Epistemic_4) %>% select(- Epistemic_6) # Why? 
# fact <- factanal(d_all, 3, rotation="varimax")
# print(fact, digits=2, cutoff=.3, sort=TRUE) # Optimal model w/3 factors 

# here we're plotting our factors (3 and 2) to visually see where the items are loading
load <- fact3$loadings[,1:3]
plot(load,type="n") # set up plot
text(load,labels=names(d_fa1),cex=.7) # add variable names

load <- fact2$loadings[,1:2]
plot(load,type="n") # set up plot
text(load,labels=names(d_fa1),cex=.7) # add variable names

# i can see here that we have two distinct groups (i prefer 2 factors to 3) where the first factor loads seasons, sun, and plants (nature/environment) and the second factor loads god's intervening with people (not the environment)
```

```{r age intervention factor sums}
# so, from here, we'll use two factors and create average scores for them

# creating our new dataframe
d_intervention <- d_all %>% dplyr::select(starts_with("help_"), contains(c("helop_friends", "age", "gender")))

# recoding intervention colomns 
d_intervention <- d_intervention %>% 
  mutate_at(vars(1:14),
   ~as.numeric(dplyr::recode(.,
    "Never"=1,
    "Only at special times"=2,
    "Pretty often"=3,
    "Always"=4,
    "always" = 4,
    "IDK" = 5)))

# recoding gender here to use in our reg
d_intervention$gender <- recode(d_intervention$gender, 'Male' = 1, 'Female'=2)

d_intervention$gender <- as.factor(d_intervention$gender)
#omitting NAs
d_intervention <- na.omit(d_intervention)

# creating sum scores for our 2 factors (environment and people)
d_intervention$environment <- rowSums(d_intervention[,c(2, 3, 4)]/3)
d_intervention$people <- rowSums(d_intervention[,c(1, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)]/11)

View(d_intervention)
```

```{r environment intervention null model}
library(arm)

# we start by creating our null model with a fixed slope and no predictors
null_model <- lm(environment ~ 1, data = d_intervention)
summary(null_model)
tab_model(null_model)
coef(null_model)
```

```{r environment intervention reg1}
reg1 <- lm(environment ~ age, data = d_intervention)
summary(reg1)
tab_model(null_model, reg1)

reg2 <- lm(environment ~ age + gender, data = d_intervention)
summary(reg2)
tab_model(null_model, reg1, reg2)

anova(null_model, reg1, reg2)

AIC(reg1, reg2)

# we can see here that our second model is better (reg2)

```

```{r environment intervention reg1 plot}
# how should we visualize this data?

g_environment <- ggplot(d_intervention,aes(y=environment,x=age)) +
  geom_point() +
  geom_jitter() +
  geom_smooth(method="lm") +
  theme_minimal()

# plotting our data without reg lines
g_environment

# You can make interactive plot easily with ggPredict() function included in ggiraphExtra package. this is me just messing around.
library(ggiraphExtra)
require(ggiraph)
require(ggiraphExtra)
require(plyr)
ggPredict(reg1,se=TRUE,interactive=TRUE)

reg1 <- lm(environment ~ age, data = d_intervention)
summary(reg1)
tab_model(null_model, reg1)

g_environment1 <- ggplot(data=d_intervention, aes(x=age, y=environment)) +
  geom_bar(stat="identity", fill="purple")+
  theme_minimal()

g_environment1

# need to add error bars to this figure

reg2 <- lm(environment ~ age + gender, data = d_intervention)
summary(reg2)
tab_model(null_model, reg1, reg2)

equation1=function(x){coef(reg2)[2]*x+coef(reg2)[1]}
equation2=function(x){coef(reg2)[2]*x+coef(reg2)[1]+coef(reg2)[3]}

g_environment2 <- ggplot(d_intervention,aes(y=environment,x=age,color=gender)) + 
        geom_point() +
        stat_function(fun=equation1,geom="line",color=scales::hue_pal()(2)[1]) +
        stat_function(fun=equation2,geom="line",color=scales::hue_pal()(2)[2]) +
        theme_minimal()

g_environment2 <- g_environment2 + geom_jitter(aes(color = gender), width = 0.5, height = 0.5)

g_environment2 + labs(x = 'Age', y = 'God intervention score - Environment')

g_environment2 + scale_fill_discrete(labels=c('Male', 'Female'))


```
