---
title: "intervention_interview_cielo"
author: "Hannah Lunkenheimer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### ii.	Effects of age (and religiosity*) (and control) on interventionist concepts – interview questions
1.	Could use linear regression if dv is sum of 4 questions. Best fit model (using AIC criterion etc)

```{r leading data, include=FALSE}

library(moonBook)
library(readr)
library(ggplot2)
library(dplyr)

# importing the data
d_all <- read_csv("data/Cielo1_MergedFull_practice.csv")

# now let's view our data
#View(d_all)

# some participant data needs to be thrown out completely according to the red rows in our CSV file, so let's remove those participants completely here (ID 129, 152, 175, and 277)
subset(d_all, id_num != "129" & id_num != "152" & id_num != "175" & id_num != "277")
# great, we've removed our 4 participants completely from our dataframe d_all and now have all of the participants we can use for analyses

```

```{r interview and sums}
# so, from here, we'll use two factors and create average scores for them

# creating our new dataframe
d_interview <- d_all %>% dplyr::select(contains(c("age", "gender", "control...6", "relig_attendserv", "relig_tradition", "rgod_happen_earth", "rgod_happen_ever", "rgod_happen_lives", "rpers_happen", "relig_pray_freq", "relig_describe_god", "relig_intervene")))

# recoding gender here to use in our reg
d_interview$gender <- dplyr::recode(d_interview$gender, 'Male' = 1, 'Female'=2)
d_interview$control...6 <- dplyr::recode(d_interview$control...6, 'Really Disagree' = 6, 'Disagree'=5, 'Kind of Disagree' = 4, 'Kind of Agree' = 3, 'Agree' = 2, 'Really Agree' = 1)
d_interview$relig_attendserv <- dplyr::recode(d_interview$relig_attendserv, 'Never' = 1, 'Less than once a year'=2, 'A few times a year' = 3, 'A few times a month' = 4, 'A few times a week' = 5, 'Daily' = 6)
d_interview$relig_tradition <- dplyr::recode(d_interview$relig_tradition, 'Not at all important' = 1, 'Minimally important'=2, 'Moderately important' = 3, 'Very important' = 4)
d_interview$rgod_happen_earth <- dplyr::recode(d_interview$rgod_happen_earth, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)
d_interview$rgod_happen_ever <- dplyr::recode(d_interview$rgod_happen_ever, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)
d_interview$rgod_happen_lives <- dplyr::recode(d_interview$rgod_happen_lives, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)
d_interview$rpers_happen <- dplyr::recode(d_interview$rpers_happen, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)
d_interview$relig_pray_freq <- dplyr::recode(d_interview$relig_pray_freq, 'Never' = 1, 'Less than once a year'=2, 'A few times a year' = 3, 'A few times a month' = 4, 'A few times a week' = 5, 'Daily' = 6, 'Multiple times a day' = 7)

d_interview$relig_describe_god <- dplyr::recode(d_interview$relig_describe_god, 'I do not believe in God' = 1, 'A non-interventionist God; one who does not attempt to influence events in human life.'=2, 'A God who used to intervene in historical or biblical times, but is not particularly involved in the workings of modern life.' = 3, 'An interventionist God; one who is sometimes involved in the workings of modern life.' = 4, 'An interventionist God; one who is intimately involved in the workings of modern life.' = 5)
d_interview$relig_intervene <- dplyr::recode(d_interview$relig_intervene, 'Absolutely not' = 1, 'Probably not'=2, 'Unsure' = 3, 'Probably yes' = 4, 'Absolutely yes' = 5)

d_interview$gender <- as.factor(d_interview$gender)
d_interview$control <- as.numeric(d_interview$control...6)
d_interview$relig_attendserv <- as.numeric(d_interview$relig_attendserv)
d_interview$relig_pray_freq <- as.numeric(d_interview$relig_pray_freq)
d_interview$relig_describe_god <- as.numeric(d_interview$relig_describe_god)
#deleting the old control...6 row
d_interview <- d_interview[,-3] 
#omitting NAs
#d_interview <- na.omit(d_interview)


# creating sum scores for our IVs
# how  often child attends services, how important, 
d_interview$religiosity <- rowSums(d_interview[, c(3, 4, 9)]/3)
d_interview$parentbeliefs <- rowSums(d_interview[, c(10, 11)]/2)
d_interview$interviewscore <- rowSums(d_interview[, c(5, 6, 7, 8)]/4)

#creating a filter to exclude IDK responses from analyses
d_interview2 <- dplyr::filter(d_interview, rgod_happen_earth != 4) 
d_interview2 <- dplyr::filter(d_interview2, rgod_happen_ever != 4) 
d_interview2 <- dplyr::filter(d_interview2, rgod_happen_lives != 4) 
d_interview2 <- dplyr::filter(d_interview2, rpers_happen != 4) 

```

```{r bar graphs of proportions of intervention score questions}
# creating our new dataframe
d_interview4 <- d_all %>% dplyr::select(contains(c("age", "gender", "rgod_happen_earth", "rgod_happen_ever", "rgod_happen_lives", "rpers_happen")))

# recoding gender here to use in our reg
d_interview4$gender <- dplyr::recode(d_interview4$gender, 'Male' = 1, 'Female'=2)
d_interview4$rgod_happen_earth <- dplyr::recode(d_interview4$rgod_happen_earth, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)
d_interview4$rgod_happen_ever <- dplyr::recode(d_interview4$rgod_happen_ever, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)
d_interview4$rgod_happen_lives <- dplyr::recode(d_interview4$rgod_happen_lives, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)
d_interview4$rpers_happen <- dplyr::recode(d_interview4$rpers_happen, 'No' = 1, 'Sometimes'=2, 'Yes' = 3, 'IDK' = 4)


d_interview4$gender <- as.factor(d_interview4$gender)

#omitting NAs
d_interview4 <- na.omit(d_interview4)

# creating sum scores for our 2 factors (environment and people)

#creating a filter to exclude IDK responses from analyses
#d_interview5 <- dplyr::filter(d_interview4, rgod_happen_earth != 4) 
#d_interview5 <- dplyr::filter(d_interview5, rgod_happen_ever != 4) 
#d_interview5 <- dplyr::filter(d_interview5, rgod_happen_lives != 4) 
#d_interview5 <- dplyr::filter(d_interview5, rpers_happen != 4) 

# let's convert our data to tall format so we can include all of the same plots on the same figure
library(reshape2)
d_interview5_reshaped <- melt(d_interview4, id.vars= c("age", "gender"))

d_interview5_reshaped$value <- as.factor(d_interview5_reshaped$value)

#let's view our tall data now
View(d_interview5_reshaped)

# here, i'm making a dataframe with frequency counts added in
d_interview5_reshaped_counts <- table(d_interview5_reshaped$value, d_interview5_reshaped$variable, d_interview5_reshaped$gender)
addmargins(d_interview5_reshaped_counts)
round(prop.table(d_interview5_reshaped_counts,2)*100,digits=0)
df_i5rc <- as.data.frame(d_interview5_reshaped_counts)

# here, i'm making a dataframe with frequency counts added in
# d_intervention_reshaped_counts <- table(d_intervention_reshaped$value, d_intervention_reshaped$variable, d_intervention_reshaped$gender)
# addmargins(d_intervention_reshaped_counts)
# round(prop.table(d_intervention_reshaped_counts,2)*100,digits=0)
# df_irc <- as.data.frame(d_intervention_reshaped_counts)
# View(df_irc)
# creating our ggplot for all exist questions including both genders together. i'm labeling it p_exist because we're making a plot for the exist questions
p_irc <- ggplot(data = d_interview5_reshaped, aes(x = variable, y = age, fill = value)) +
       geom_bar(stat = "identity", width = .5) +
      theme_classic() +
      labs(title="Children's responses to God interventionist frequency questions", x ="Item", y = "Counts", fill = "Response") +
      theme(axis.text.x = element_text(angle=90))

# fixing the x axis labels
p_irc <- p_irc + scale_fill_discrete(labels=c("1" = "No", "2" = "Sometimes", "3" = "Yes", "4" = "I don't know"))

# faceting by gender
# p_irc <- p_irc + facet_wrap(~Var3, ncol = 1) +
#     theme(panel.spacing = unit(1, "lines"))

p_irc

```

```{r intervention score x gender bar figure}

# here, i'm making a dataframe with frequency counts added in
d_interview_reshaped_counts <- table(d_interview5_reshaped$value, d_interview5_reshaped$variable, d_interview5_reshaped$gender)
addmargins(d_interview_reshaped_counts)
round(prop.table(d_interview_reshaped_counts,2)*100,digits=0)
df_ivrc <- as.data.frame(d_interview_reshaped_counts)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442")
cbPalette2 <- c("#999999", "#E69F00", "#009E73", "#F0E442")

#Turn your 'treatment' column into a character vector
df_ivrc$Var2 <- as.character(df_ivrc$Var2)
#Then turn it back into a factor with the levels in the correct order
df_ivrc$Var2 <- factor(df_ivrc$Var2, levels=c("rgod_happen_earth", "rgod_happen_ever", "rgod_happen_lives", "rpers_happen"))

# creating our ggplot for all exist questions including both genders together. i'm labeling it p_exist because we're making a plot for the exist questions
g_ivrc <- ggplot(data = df_ivrc, aes(x = Var2, y = Freq, fill = Var1)) +
    scale_fill_brewer(palette = "Paired", labels=c("1" = "No", "2" = "Sometimes", "3" = "Yes", "4" = "I don't know")) +
       geom_bar(stat = "identity", width = .5) +
      theme_classic() +
      labs(title="Figure 1. Children's responses to God intervention questions", x = "Question", y = "Counts", fill = "Response") +
      theme(axis.text.x = element_text(angle=01))

#g_irc <- g_irc + scale_fill_discrete(labels=c("1" = "Never", "2" = "Only on special occasions", "3" = "Pretty #often", "4" = "Always", "5" = "I don't know"))


# changing the label names
g_ivrc <- g_ivrc + scale_x_discrete(labels=c("rgod_happen_earth" = "On earth", "rgod_happen_ever" = "Ever", "rgod_happen_lives" = "People's\nlives", "rpers_happen" = "Your\nlife" ))

g_ivrc <- g_ivrc + theme(legend.position="bottom")

g_ivrc


```

```{r visualizing interview score, items, and age}

g_interviewage <- ggplot(d_interview2,aes(y=interviewscore,x=age, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm') +
  scale_color_discrete(labels=c('Male', 'Female'))
g_rgod_happen_earth <- ggplot(d_interview2,aes(y=rgod_happen_earth,x=age, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm') +
  scale_color_discrete(labels=c('Male', 'Female'))
g_rgod_happen_ever <- ggplot(d_interview2,aes(y=rgod_happen_ever,x=age, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female'))
g_rgod_happen_lives <- ggplot(d_interview2,aes(y=rgod_happen_lives,x=age, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female'))
g_rpers_happen <- ggplot(d_interview2,aes(y=rpers_happen,x=age, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female')) 
g_controll <- ggplot(d_interview2,aes(y=interviewscore,x=control, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female')) 

g_interviewage
g_rgod_happen_earth
g_rgod_happen_ever
g_rgod_happen_lives
g_controll

g_rpers_happen <- ggplot(d_interview2,aes(y=rpers_happen,x=age, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female')) 

g_rpers_happen + 
    labs(title="Figure X. Regression with control in model as predictor", x = "Age", y = "Total intervention score") +
    scale_color_manual('Gender', values = cbPalette, labels = c('Male', 'Female')) +
    theme(legend.position="bottom")


####################################
# HL CHECK ADULTS RESPONSE TO PERSONAL INTERVENTION IN LIFE QUESTION X=CHILDS Y=PARENTS
####################################
cbPalette <- c("#999999","#E69F00","#56B4E9","#009E73", "#F0E442","#0072B2","#D55E00","#CC79A7")

g_rgodhappenall <- ggplot(d_interview2, aes(age,interviewscore)) + 
  geom_jitter(height = .1, width = .1) +
  geom_smooth(aes(age,control), color="56B4E9", method="lm",se=FALSE)
  
  #geom_smooth(aes(age,religiosity), color="#56B4E9", method="lm",se=FALSE)
  #geom_smooth(aes(age,religiosity), color="#009E73", method="lm",se=FALSE)
  #geom_smooth(aes(age,rpers_happen), color="#F0E442", method="lm",se=FALSE) +
  #geom_smooth(aes(age,control), color="#0072B2", method="lm",se=FALSE)



g_rgodhappenall <- g_rgodhappenall + theme_minimal() +
  labs(title="Figure Y", x = "Age", y = "Total intervention score")

g_rgodhappenall
```


```{r poster fig}
#idrk what i'm trying to show here?
g_poster <- ggplot(d_interview2, aes(age,religiosity)) + 
  geom_jitter(color="#999999") +
  geom_smooth(aes(age,religiosity), color="black", method="lm",se=FALSE) +
  geom_smooth(aes(age,relig_describe_god), color="#56B4E9", method="lm",se=FALSE) +
  geom_smooth(aes(age,relig_intervene), color="#009E73", method="lm",se=FALSE) +
  geom_smooth(aes(age,rpers_happen), color="#F0E442", method="lm",se=FALSE) +
  geom_smooth(aes(age,control), color="#0072B2", method="lm",se=FALSE) +
  scale_color_manual(values=c("black"="#000000", "#56B4E9"="#56B4E9", "#009E73"="#009E73", "#F0E442"="#F0E442", "#0072B2"="#0072B2"),
  labels=c("R. God happen lives", "R. God happen ever", "R. God happen earth", "R. pers. happen", "Control")) + 
  labs(color="Legend Title")

g_poster
```

```{r visualizing interview score, items, and religiosity}

rg_interview <- ggplot(d_interview2,aes(y=interviewscore,x=religiosity, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female'))
rg_rgod_happen_earth <- ggplot(d_interview2,aes(y=rgod_happen_earth,x=religiosity, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female'))
rg_rgod_happen_ever <- ggplot(d_interview2,aes(y=rgod_happen_ever,x=religiosity, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female'))
rg_rgod_happen_lives <- ggplot(d_interview2,aes(y=rgod_happen_lives,x=religiosity, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female'))
rg_rpers_happen <- ggplot(d_interview2,aes(y=rpers_happen,x=religiosity, color=gender)) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  geom_smooth(method='lm')+
  scale_color_discrete(labels=c('Male', 'Female'))

rg_interview
rg_rgod_happen_earth
rg_rgod_happen_ever
rg_rgod_happen_lives
rg_rpers_happen
```

```{r reg interviews}
library(sjPlot)
# we start by creating our null model with a fixed slope and no predictors
null_model <- lm(interviewscore ~ 1, data = d_interview2)
summary(null_model)
coef(null_model)

reg1 <- lm(interviewscore ~ age, data = d_interview2)
summary(reg1)
coef(reg1)

reg2 <- lm(interviewscore ~ age + gender, data = d_interview2)
summary(reg2)
coef(reg2)

reg3 <- lm(interviewscore ~ age + gender + religiosity, data = d_interview2)
summary(reg3)
anova(reg3)
coef(reg3)

reg4 <- lm(interviewscore ~ age + gender + religiosity + control, data = d_interview2)
summary(reg4)
coef(reg4)

reg5 <- lm(interviewscore ~ age + gender + religiosity + control + parentbeliefs + age*gender + age*religiosity + gender*religiosity + age*control + gender*control + religiosity*control + parentbeliefs*age + parentbeliefs*gender + parentbeliefs*religiosity + parentbeliefs*control, data = d_interview2)
summary(reg5)
coef(reg5)

# i think this model is the best!
reg6 <- lm(interviewscore ~ age + gender + religiosity + control + religiosity*control + parentbeliefs*age, data = d_interview2)
summary(reg6)
anova(reg6)
coef(reg6)
tab_model(reg6)

reg7 <- lm(interviewscore ~ age + gender + religiosity + control + parentbeliefs*age, data = d_interview2)
summary(reg7)
anova(reg7)
coef(reg7)
tab_model(reg7)

reg8 <- lm(interviewscore ~ age + gender + religiosity + control + parentbeliefs, data = d_interview2)
summary(reg8)
AIC(reg4)
AIC(reg5)
AIC(reg6)
AIC(reg7)
AIC(reg8)

tab_model(reg4, reg5, reg6)


######################
# TRY AND MAKE THIS A FIGURE reg6

```

```{r reg plotted}

# religiosity and control are not statistically correlated with eachother
library("ggpubr")
ggscatter(d_interview2, x = "religiosity", y = "control", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Religiosity", ylab = "Perceived control")

shapiro.test(d_interview$religiosity)
shapiro.test(d_interview$control)

ggqqplot(d_interview$religiosity, ylab = "religiosity")

```
```{r interaction plot}
library(sjPlot)
library(sjmisc)
library(ggplot2)

theme_set(theme_sjplot())

# make categorical
#efc$c161sex <- to_factor(efc$c161sex)

# fit model with interaction
interaction <- plot_model(reg6, type = "pred", colors = c("#a5cae0", "#1c6996", "#b2df8a", "#33a02b", "#fb9a99", "#e3211c"), terms = c("religiosity", "control"), axis.title = c("Religiosity", "Intervention score"), legend.title = "Perceived control", ) + theme_minimal()

interaction <- interaction + theme(legend.position="bottom")

interaction <- interaction + guides(col = guide_legend(nrow=1))

interaction 

interaction + ggplot2::scale_color_discrete(name = "Perceived control", labels = c("Low", "2", "3", "4", "5", "High"))

```
Parent questions: 
How often child attends services
Important?
How often child prays?
Parent idea of god
Has God intervened?

Family Religiosity:  1, 2, 3
Parent intervention: 4, 5
```{r regression for age, religiosity and control on intervention score}



```
