---
title: "cielo1_irr"
author: "Hannah Lunkenheimer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(irr)
library(tidyverse)
library(readxl)
library(reshape2)

paola <- read_excel("../data/data_archive/paola_cielomanuscript.xlsx")

paola <- paola %>%
  slice(4:98) %>%
  mutate_all(as.numeric)

helen <- read_excel("../data/data_archive/helen_cielomanuscript.xlsx")

helen <- helen %>%
  slice(4:98) %>%
  mutate_all(as.numeric)

paola_stacked <- gather(paola, key = "variable_name", value = "value", -1)
helen_stacked <- gather(helen, key = "variable_name", value = "value", -1)

kappa_result <- kappa2(paola_stacked$value, helen_stacked$value, weight = "unweighted")
```

```{r checking paola's creation}


```

```{r irr}
d_paola <- melt(d_paola, "V1")
d_helen <- melt(d_helen, "V1")

total <- merge(d_paola, d_helen,by="V1")

#for (dimension in 1:78) {
#    v = paste0("V", dimension)
#    print(irr::kappa2(cbind(d_helen[, v], d_paola[, v])))
#}

#overall IRR is .92
kappa2(total[, c("value.x", "value.y")], weight = "unweighted")

```
