---
title: "Descriptive Data for Cielo"
author: "Hannah Lunkenheimer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set working directory
knitr::opts_knit$set(root.dir = '/Documents/Github/cielo')

# Libraries 
library(tidyverse)
library(here)
library(psych)
library(nFactors)
library(lme4)
library(nlme)
library(FactoMineR)
library(sem)
library(ggplot2)
library(dplyr)
library(lavaan) # for factor analysis 
library(performance) # for model performance
library(texreg)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(lattice)
library(readr)

```

```{r importing the data}
# importing the data
d_all <- read_csv("data/Cielo1_MergedFull_practice.csv")

# now let's view our data
#View(d_all)

# some participant data needs to be thrown out completely according to the red rows in our CSV file, so let's remove those participants completely here (ID 129, 152, 175, and 277)
d_all <- subset(d_all, id_num != "129" & id_num != "152" & id_num != "175" & id_num != "277")
# great, we've removed our 4 participants completely from our dataframe d_all and now have all of the participants we can use for analyses

```

```{r exist forming subset data}

# here, we're creating a new dataframe for a subset of our data that we want to look at (the exist questions)
d_exist <- dplyr::select(d_all, gender, exist_germs, exist_tooth, exist_vitamins, exist_merm, exist_elf, exist_fairy,
                         exist_soul, exist_god, exist_santa, exist_elf, contains("id_num"))

d_exist<-subset(d_exist, gender!="Other")

```

```{r parent religiosity}
d_all$relig_parent1 <- recode(d_all$relig_parent1, 'Other Christian (Non-denominational)' = 'Other Christian', 'none' = 'Atheist', 'other christian' = 'Other Christian', 'protestant' = 'Protestant', 'Protestant,Other Christian' = 'Protestant', 'None' = 'Atheist', 'Not Answered' = 'Not answered', 'Athiest' = 'Atheist', 'Catholic/Buddhist' = 'Catholic', 'Other Christian,Athiest' = 'Other Christian', 'Other Christian/Atheist' = 'Other Christian')

d_all$relig_parent2 <- recode(d_all$relig_parent2, 'Other Christian (Non-denominational)' = 'Other Christian', 'none' = 'Atheist', 'other christian' = 'Other Christian', 'protestant' = 'Protestant', 'Protestant,Other Christian' = 'Protestant', 'Athiest' = 'Atheist', 'Not Answered' = 'Not answered', 'Athiest' = 'Atheist', 'Catholic/Buddhist' = 'Catholic', 'Other Christian,Athiest' = 'Other Christian', 'Other Christian/Atheist' = 'Other Christian', 'catholic' = 'Catholic', 'Catholic,Athiest' = 'Catholic', 'catholic/other christian' = 'Catholic', 'Jewish/Atheist' = 'Other', 'None' = 'Atheist', 'Not Answered' = 'Not answered',  'protestant' = 'Protestant', 'Protestant,Athiest' = 'Protestant', 'Protestant,Other Christian' = 'Protestant', 'other Christian' = 'Other Christian')

# recoding schooling
d_all$school <- recode(d_all$school, 'homeschool' = 'Homeschool', "Not Answered" = 'Not answered', 'religious' = 'Religious', 'secular' = 'Secular')

#recode into Protestant, Catholic, Christian other and so on
#checking to see if kids are raised in a 2 relig household

ifelse(d_all$relig_parent1==d_all$relig_parent2,"Yes","No")

```

```{r exist descriptives by item}
#viewing our new dataframe with our exist questions subset of data
View(d_exist)

existgerms_plot <- ggplot(d_exist, aes(exist_germs)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Are germs real?") +
  theme_light()

existvit_plot <- ggplot(d_exist, aes(exist_vitamins)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Are vitamins real?") +
  theme_light()

existmerm_plot <- ggplot(d_exist, aes(exist_merm)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Are mermaids real?") +
  theme_light()

existelf_plot <- ggplot(d_exist, aes(exist_elf)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Are elves real?") +
  theme_light()

existfairy_plot <- ggplot(d_exist, aes(exist_fairy)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Are fairies real?") +
  theme_light()

existsoul_plot <- ggplot(d_exist, aes(exist_soul)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Are sould real?") +
  theme_light()

existgod_plot <- ggplot(d_exist, aes(exist_god)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Is God real?") +
  theme_light()

existsanta_plot <- ggplot(d_exist, aes(exist_santa)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Is Santa real?") +
  theme_light()

existtooth_plot <- ggplot(d_exist, aes(exist_tooth)) +
  geom_bar(fill='light blue') +
  labs(x='Scale', y="Participants", title ="Is the tooth fairy real?") +
  theme_light()

# calling our figures
existgerms_plot
existvit_plot
existmerm_plot
existelf_plot
existfairy_plot
existsoul_plot
existgod_plot 
existsanta_plot
existtooth_plot
```

```{r exist x gender bar figure}
# let's convert our data to tall format so we can include all of the same plots on the same figure
library(reshape2)
d_exist <- melt(d_exist, id.vars= c("id_num", "gender"))

#let's view our tall data now
#View(d_exist)

# here, i'm making a dataframe with frequency counts added in
d_exist_counts <- table(d_exist$value, d_exist$variable, d_exist$gender)
addmargins(d_exist_counts)
round(prop.table(d_exist_counts,2)*100,digits=0)
df_ec <- as.data.frame(d_exist_counts)
df_ec
# creating our ggplot for all exist questions including both genders together. i'm labeling it p_exist because we're making a plot for the exist questions
p_exist <- ggplot(data = df_ec, aes(x = Var2, y = Freq, fill = Var1)) +
       geom_bar(stat = "identity", width = .5) +
      geom_text(aes(label = Freq), position = position_stack(vjust = 0.5), color="black", size=3) +
      theme_classic() +
      labs(title="Children's responses to real or pretend questions", x ="Item", y = "Counts", fill = "Response") +
      theme(axis.text.x = element_text(angle=20))

# fixing the x axis labels
p_exist <- p_exist + scale_x_discrete(labels=c("exist_germs" = "Germs", "exist_tooth" = "Tooth Fairy", "exist_vitamins" = "Vitamins", "exist_merm" = "Mermaids", "exist_elf" = "Elves", "exist_fairy" = "Fairies", "exist_soul" = "Souls", "exist_god" = "God", "exist_santa" = "Santa"))

# faceting by gender
p_exist <- p_exist + facet_wrap(~Var3, ncol = 1) +
    theme(panel.spacing = unit(1, "lines"))

p_exist + coord_flip()

# creating our ggplot for all exist questions including both genders together. i'm labeling it p_exist because we're making a plot for the exist questions
p_exist2 <- ggplot(data = df_ec, aes(x = Var2, y = Freq, color = Var1)) +
      geom_point(stat = "identity", width = .5) +
      geom_jitter() +
      geom_text(aes(label = Freq), position = position_stack(vjust = 0.5), color="black", size=3) +
      theme_classic() +
      labs(title="Children's responses to real or pretend questions", x ="Item", y = "Counts", fill = "Response") +
      theme(axis.text.x = element_text(angle=20))

# fixing the x axis labels
p_exist2 <- p_exist2 + scale_x_discrete(labels=c("exist_germs" = "Germs", "exist_tooth" = "Tooth \n Fairy", "exist_vitamins" = "Vitamins", "exist_merm" = "Mermaids", "exist_elf" = "Elves", "exist_fairy" = "Fairies", "exist_soul" = "Souls", "exist_god" = "God", "exist_santa" = "Santa"))

# faceting by gender
p_exist2 <- p_exist2 + facet_wrap(~Var3, ncol = 1) +
    theme(panel.spacing = unit(1, "lines")) 

p_exist2
```

```{r exist x age bar figure}
# here, we're creating a new dataframe for a subset of our data that we want to look at (the exist questions)
d_exist2 <- dplyr::select(d_all, age, exist_germs, exist_tooth, exist_vitamins, exist_merm, exist_elf, exist_fairy,
                         exist_soul, exist_god, exist_santa, exist_elf, contains("id_num"))

#d_exist<-subset(d_exist, gender!="Other")

# let's convert our data to tall format so we can include all of the same plots on the same figure
library(reshape2)
d_exist2 <- melt(d_exist2, id.vars= c("id_num", "age"))

#let's view our tall data now
#View(d_exist2)

# here, i'm making a dataframe with frequency counts added in
d_exist_counts2 <- table(d_exist2$value, d_exist2$variable, d_exist2$age)
#d_exist_counts2 <- addmargins(d_exist_counts2)
#d_exist_counts2 <- round(prop.table(d_exist_counts2,2)*100,digits=0)

df_ec2 <- as.data.frame(d_exist_counts2)

#df_ec2 <- subset(df_ec2, Var1!="Sum" && Var2!="Sum" && Var3!="Sum")
#df_ec2 <- subset(df_ec2, Var3!="Sum")

# creating our ggplot for all exist questions including both genders together. i'm labeling it p_exist becaues we're making a plot for the exist questions
p_exist2 <- ggplot(data = df_ec2, aes(x = Var2, y = Freq, fill = Var3)) +
       geom_bar(stat = "identity", width = .9) +
        geom_text(aes(label = Freq), position = position_stack(vjust = 0.5), color="black", size=2) +
      theme_classic() +
      labs(title="Children's responses to real or pretend questions", x ="Item", y = "Counts", fill = "Age") +
      theme(axis.text.x = element_text(angle=20)) +
  coord_flip()

# fixing the x axis labels
p_exist2 <- p_exist2 + scale_x_discrete(labels=c("exist_germs" = "Germs", "exist_tooth" = "Tooth Fairy", "exist_vitamins" = "Vitamins", "exist_merm" = "Mermaids", "exist_elf" = "Elves", "exist_fairy" = "Fairies", "exist_soul" = "Souls", "exist_god" = "God", "exist_santa" = "Santa"))

# faceting by age
p_exist2 <- p_exist2 + facet_wrap(~Var1, nrow=2) +
    theme(panel.spacing = unit(1, "lines"))

p_exist2

##############################################3
## HL try and stretch the facets (length) so the numbers are more clear & nice looking
```

```{r clustered bar chart for real/pretend questions}

ggplot(data = df_ec2, aes(Var2, Freq)) + 
  geom_bar(aes(fill = Var3), stat = "identity", position = "dodge") +
      theme_minimal() +
      labs(title="Children's responses to real or pretend questions", x ="Item", y = "Counts", fill = "Age") +
      scale_x_discrete(labels=c("exist_germs" = "Germs", "exist_tooth" = "Tooth Fairy", "exist_vitamins" = "Vitamins", "exist_merm" = "Mermaids", "exist_elf" = "Elves", "exist_fairy" = "Fairies", "exist_soul" = "Souls", "exist_god" = "God", "exist_santa" = "Santa")) +
    scale_fill_brewer(palette = "Paired") +
  facet_wrap(~Var1, ncol = 1)

```
