---
title: "spp_analyses_cielo"
author: "Hannah Lunkenheimer"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      cache = TRUE)

library(moonBook)
library(dplyr)
library(readr)
library(ggplot2)
library(sjPlot)
library(reshape2)
library(ggsignif)
# importing the data
d_all <- read_csv("data/Cielo1_MergedFull_practice.csv")

# now let's view our data
#View(d_all)

# some participant data needs to be thrown out completely according to the red rows in our CSV file, so let's remove those participants completely here (ID 129, 152, 175, and 277)
d_all <- subset(d_all, id_num != "129" & id_num != "152" & id_num != "175" & id_num != "277")
# great, we've removed our 4 participants completely from our dataframe d_all and now have all of the participants we can use for analyses

```

```{r age intervention factor sums}
# so, from here, we'll use two factors and create average scores for them

# creating our new dataframe
d_intervention <- d_all %>% dplyr::select(starts_with("help_"), contains(c("helop_friends", "age", "gender", "control...6", "relig_attendserv", "relig_tradition", "id_num")))

# recoding intervention colomns 
d_intervention <- d_intervention %>% 
  mutate_at(vars(1:14),
   ~as.numeric(dplyr::recode(.,
    "Never"=1,
    "Only at special times"=2,
    "Pretty often"=3,
    "Always"=4,
    "always" = 4,
    "IDK" = 5)))

# recoding gender here to use in our reg
d_intervention$gender <- dplyr::recode(d_intervention$gender, 'Male' = 1, 'Female'=2)
d_intervention$control...6 <- dplyr::recode(d_intervention$control...6, 'Really Disagree' = 6, 'Disagree'=5, 'Kind of Disagree' = 4, 'Kind of Agree' = 3, 'Agree' = 2, 'Really Agree' = 1)
d_intervention$relig_attendserv <- dplyr::recode(d_intervention$relig_attendserv, 'Never' = 1, 'Less than once a year'=2, 'A few times a year' = 3, 'A few times a month' = 4, 'A few times a week' = 5, 'Daily' = 6)
d_intervention$relig_tradition <- dplyr::recode(d_intervention$relig_tradition, 'Not at all important' = 1, 'Minimally important'=2, 'Moderately important' = 3, 'Very important' = 4)



d_intervention$gender <- as.factor(d_intervention$gender)
d_intervention$control <- as.numeric(d_intervention$control...6)
d_intervention$relig_attendserv <- as.numeric(d_intervention$relig_attendserv)
d_intervention$relig_tradition <- as.numeric(d_intervention$relig_tradition)

#omitting NAs
d_intervention <- na.omit(d_intervention)

# creating sum scores for our 2 factors (environment and people)
d_intervention$environment <- rowSums(d_intervention[,c(2, 3, 4)]/3) #plants, sun, seasons
d_intervention$psych <- rowSums(d_intervention[,c(6, 8, 11, 12)]/4) #dreams, happy, brave decisions
d_intervention$health <- rowSums(d_intervention[,c(1, 13)]/2) #sick, safe
d_intervention$outcome <- rowSums(d_intervention[,c(7, 9, 10)]/3) #job, sports, find
d_intervention$social <- rowSums(d_intervention[,c(5, 14)]/2) #love, friends

d_intervention$people <- rowSums(d_intervention[,c(1, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)]/11)
d_intervention$totalinter <- rowSums(d_intervention[, c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)]/14)
d_intervention$religiosity <- rowSums(d_intervention[, c(18, 19)]/2)

#creating a filter to exclude IDK responses from analyses
d_intervention2 <- dplyr::filter(d_intervention, help_plants != 5 | help_love != 5) 
d_intervention2 <- dplyr::filter(d_intervention2, help_love != 5) 


```

```{r comparing mean diffs between factors}
#making the daataframe long
longdata <- d_intervention2 %>% dplyr::select(starts_with("outcome"), starts_with("health"), starts_with("psych"), starts_with("social"), starts_with("environment"), starts_with("id_num")) 
longdata <- melt(longdata, id.vars= c("id_num"))

ggplot(data = longdata, mapping = aes(x = variable, y = value, color = variable)) + 
  geom_boxplot() +
  geom_signif(comparisons = list(c("outcome", "health")), y_position = 4.00,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("outcome", "psych")), y_position = 4.25,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("outcome", "environment")), y_position = 4.5,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("social", "health")), y_position = 4.75,
              map_signif_level=TRUE) +
  geom_signif(comparisons = list(c("social", "psych")), y_position =5,
              map_signif_level=TRUE) +
  theme_minimal() +
  scale_color_brewer(palette= "Paired") +
  theme(legend.position = "none") +
  labs(title = "Intervention Cluster Mean Scores", x = "Domain", y = "Response") + 
  scale_x_discrete(labels=c("outcome" = "Achievement", "health" = "Health", "social" = "Social", "psych" = "Psychology", "environment" = "Nature"))



# Compute the analysis of variance
anova1 <- aov(value ~ variable, data = longdata)
# Summary of the analysis
summary(anova1)
TukeyHSD(anova1)


# computing anova for each cluster

```

```{r environment intervention regs}
library(arm)

# we start by creating our null model with a fixed slope and no predictors
null_model <- lm(environment ~ 1, data = d_intervention2)
summary(null_model)
tab_model(null_model)
coef(null_model)

reg1 <- lm(environment ~ age, data = d_intervention2)
summary(reg1)
tab_model(null_model, reg1)

reg2 <- lm(environment ~ age + gender, data = d_intervention2)
summary(reg2)
tab_model(null_model, reg1, reg2)

reg3 <- lm(environment ~ age + gender + control, data = d_intervention2)
summary(reg3)
tab_model(null_model, reg1, reg2, reg3)

reg4 <- lm(environment ~ age + gender + control + religiosity + age*gender + age*control + gender*control + age*religiosity + gender*religiosity + control*religiosity, data = d_intervention2)
summary(reg4)
tab_model(null_model, reg1, reg2, reg3, reg4)

reg5 <- lm(environment ~ age + gender + control + religiosity  + gender*control, data = d_intervention2)
AIC(reg1, reg2, reg3, reg4, reg5)
anova(reg1, reg2, reg3, reg4, reg5)
summary(reg5)

tab_model(reg1, reg4, reg5)
tab_model(reg5)
AIC(reg1, reg4, reg5)

```

```{r psych intervention regs}
library(arm)

# we start by creating our null model with a fixed slope and no predictors
null_modelpsych <- lm(psych ~ 1, data = d_intervention2)
summary(null_modelpsych)
tab_model(null_modelpsych)
coef(null_modelpsych)

reg1psych <- lm(psych ~ age, data = d_intervention2)
summary(reg1psych)
tab_model(null_modelpsych, reg1psych)

reg2psych <- lm(psych ~ age + gender, data = d_intervention2)
summary(reg2psych)
tab_model(null_modelpsych, reg1psych, reg2psych)

reg3psych <- lm(psych ~ age + gender + control, data = d_intervention2)
summary(reg3psych)
tab_model(null_modelpsych, reg1psych, reg2psych, reg3psych)

reg4psych <- lm(psych ~ age + gender + control + religiosity + age*gender + age*control + gender*control + age*religiosity + gender*religiosity + control*religiosity, data = d_intervention2)
summary(reg4psych)
tab_model(null_modelpsych, reg1psych, reg2psych, reg3psych, reg4psych)

reg5psych <- lm(psych ~ age + gender + control + religiosity  + gender*control, data = d_intervention2)
AIC(reg1psych, reg2psych, reg3psych, reg4psych, reg5psych)
anova(reg1psych, reg2psych, reg3psych, reg4psych, reg5psych)
summary(reg5psych)

tab_model(reg1psych, reg4psych, reg5psych)
tab_model(reg5psych)
AIC(reg1psych, reg4psych, reg5psych)

```

```{r social intervention regs}
library(arm)

# we start by creating our null model with a fixed slope and no predictors
null_modelsocial <- lm(social ~ 1, data = d_intervention2)
summary(null_modelsocial)
tab_model(null_modelsocial)
coef(null_modelsocial)

reg1social <- lm(social ~ age, data = d_intervention2)
summary(reg1social)
tab_model(null_modelsocial, reg1social)

```

```{r outcome intervention regs}
library(arm)

# we start by creating our null model with a fixed slope and no predictors
null_modeloutcmoe <- lm(outcome ~ 1, data = d_intervention2)
summary(null_modeloutcmoe)
tab_model(null_modeloutcmoe)
coef(null_modeloutcmoe)

reg1outcome <- lm(outcome ~ age, data = d_intervention2)
summary(reg1outcome)
tab_model(null_modeloutcmoe, reg1outcome)

```

```{r health intervention regs}
library(arm)

# we start by creating our null model with a fixed slope and no predictors
null_modelhealth <- lm(health ~ 1, data = d_intervention2)
summary(null_modelhealth)
tab_model(null_modelhealth)
coef(null_modelhealth)

reg1health <- lm(health ~ age, data = d_intervention2)
summary(reg1health)
tab_model(null_modelhealth, reg1health)

```

Parent questions: 
How often child attends services
Important?
How often child prays?
Parent idea of god
Has God intervened?

Family Religiosity:  1, 2, 3
Parent intervention: 4, 5

```{r parent intervention}


```